apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ihi999bgn-nodejs
  janus-idp.io/tekton: ihi999bgn-nodejs
  backstage.io/kubernetes-id: ihi999bgn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ihi999bgn-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
